apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: fortune 
spec: 
 replicas: 5
 selector:
   matchLabels:
     app: fortune
 template:
  metadata:
   labels:
      app: fortune
  spec:
     containers:
     - name: web 
       image: ilkiformation/webapache:v1
       ports:
       - containerPort: 80 
       - containerPort: 22
     - name: genrator
       image: ilkiformation/fortunegen:v1
   