apiVersion: v1
kind: Pod
metadata:
  name: frontweb
  labels:
    name: frontweb
spec:
  containers:
  - name: frontweb
    image: ilkiformation/simplefrontweb:v1
    ports:
      - containerPort: 80
    volumeMounts:
    - name: vhost
      mountPath: /etc/apache2/sites-available/
    - name: html
      mountPath: /var/www/wimpleweb/
    - name: css
      mountPath: /var/www/simpleweb/css
    - name: templates
      mountPath: /var/www/simpleweb/templates
  volumes:
   - name: vhost
     configMap:
       name: frontweb-vhost
   - name: html
     configMap:
       name: frontweb-html
   - name: css
     configMap:
       name: frontweb-css
   - name: templates
     configMap:
       name: frontweb-templates
       