apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: fortune 
spec: 
 selector:
   matchLabels:
     app: fortune
 template:
  metadata:
   labels:
      app: fortune
  spec:
     containers:
     - name: web 
       image: ilkiformation/webapache:v1
       ports:
       - containerPort: 80 
       - containerPort: 22
     - name: genrator
       image: ilkiformation/chuckgen:v1
   