apiVersion: v1 
kind: Pod 
metadata:
  name: chuck
  labels:
    app: chuck
spec:
 containers:
 - name: web
   image: ilkiformation/webapache:v1
   ports:
    - containerPort: 80 
    - containerPort: 22
   volumeMounts:
     - mountPath: /var/www/html
       name: html
 - name: generator
   image: ilkiformation/chuckgenvolume:v1
   volumeMounts:
     - mountPath: /tmp
       name: html
 volumes:
 - name: html
   emptyDir: {}
